project:
  type: website

website:
  title: "Quarto Playground"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - notes.qmd
      - python.ipymb
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



